# Generated by Django 2.1.7 on 2019-03-09 14:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_Rejected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant_Addr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_House_No', models.CharField(default='0000', max_length=10)),
                ('A_Street', models.CharField(default='0000', max_length=15)),
                ('A_Locality', models.CharField(default='0000', max_length=15)),
                ('A_City', models.CharField(max_length=15)),
                ('A_PINCode', models.IntegerField(default=0)),
                ('A_State', models.CharField(max_length=15)),
                ('A_Country', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_ID', models.CharField(max_length=10)),
                ('Applicant_Name', models.CharField(max_length=30)),
                ('Applicant_Age', models.IntegerField(default=0)),
                ('Applicant_Gender', models.CharField(max_length=1)),
                ('Applicant_Mobile_No', models.BigIntegerField(default=0)),
                ('Applicant_Email', models.EmailField(default=None, max_length=254)),
                ('Applicant_PAN', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Application_Details',
            fields=[
                ('Application_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Amount', models.FloatField(default=None)),
                ('Tenure', models.IntegerField(default=0)),
                ('Date_Application', models.DateTimeField(default=datetime.datetime.now)),
                ('Purpose', models.TextField(max_length=1)),
                ('Frequency', models.IntegerField(default=0)),
                ('Status', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Approved_Appln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField(default=0)),
                ('Tenure', models.IntegerField(default=0)),
                ('Status', models.CharField(max_length=2)),
                ('DueDate', models.DateField(default=datetime.datetime.now)),
                ('Application_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Application_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('Assets_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Fixed_Assets', models.FloatField(default=0)),
                ('Intangible_Assets', models.FloatField(default=0)),
                ('Current_Assets', models.FloatField(default=0)),
                ('Non_Current_Assets', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Blacklisted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applicant_ID', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Addr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_House_No', models.CharField(default='0000', max_length=10)),
                ('B_Street', models.CharField(default='0000', max_length=15)),
                ('B_Locality', models.CharField(default='0000', max_length=15)),
                ('B_City', models.CharField(max_length=15)),
                ('B_PINCode', models.IntegerField(default=0)),
                ('B_State', models.CharField(max_length=15)),
                ('B_Country', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Business_Details',
            fields=[
                ('B_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('B_Type', models.CharField(max_length=20)),
                ('B_name', models.TextField(max_length=30)),
                ('B_PAN', models.CharField(max_length=10)),
                ('B_contact', models.BigIntegerField(default=0)),
                ('B_Estb', models.DateField(default=datetime.datetime.now)),
                ('Application_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Application_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('Capital_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Issued_Capital', models.FloatField(default=0)),
                ('Paid_Up_Capital', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Flows',
            fields=[
                ('Cash_Flows_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Operations_Activities', models.FloatField(default=0)),
                ('Investing_Activities', models.FloatField(default=0)),
                ('Financing_Activities', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Disbursed_appl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.FloatField(default=0)),
                ('Disbursed_date', models.DateField(default=datetime.datetime.now)),
                ('Due_date', models.DateField(default=datetime.datetime.now)),
                ('S_Interest', models.FloatField(default=0)),
                ('Due_Amount', models.FloatField(default=0)),
                ('Application_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Application_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KTP', models.TextField(default=None)),
                ('Family_Card', models.TextField(default=None)),
                ('Company_Estb_Details', models.TextField(default=None)),
                ('NPWP', models.TextField(default=None)),
                ('Bank_Statement', models.TextField(default=None)),
                ('Applicant_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Applicant_Details')),
                ('Application_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Application_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('Financial_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Application_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Application_Details')),
                ('Assets_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Assets')),
                ('B_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Business_Details')),
                ('Capital_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Capital')),
                ('Cash_Flows_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Cash_Flows')),
            ],
        ),
        migrations.CreateModel(
            name='Installments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DueDate', models.DateField(default=datetime.datetime.now)),
                ('Payment_Date', models.DateField(blank=True, null=True)),
                ('Base_Amount', models.FloatField(default=0)),
                ('S_Interest', models.FloatField(default=0)),
                ('Total_Amount', models.FloatField(default=0)),
                ('Link', models.BooleanField(blank=True, default=False)),
                ('Link_Time', models.DateTimeField(blank=True, null=True)),
                ('Application_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Application_Details')),
            ],
        ),
        migrations.CreateModel(
            name='Investor_earnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earnings', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Investor_lending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_available', models.FloatField(default=0)),
                ('Last_Update', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Investor_main',
            fields=[
                ('Inv_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Amount_Invested', models.FloatField()),
                ('Date_Investment_Initial', models.DateTimeField(default=datetime.datetime.now)),
                ('Date_Last_Cumulative', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('Liabilities_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Term_Liabilities', models.FloatField(default=0)),
                ('Current_Liabilities', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reject_reason',
            fields=[
                ('Reason_code', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('Reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('Reserves_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Subsidy_Gov', models.FloatField(default=0)),
                ('General_Reserves', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Inv_ID', models.CharField(max_length=10)),
                ('Application_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Application_Details')),
            ],
        ),
        migrations.CreateModel(
            name='User_Credentials',
            fields=[
                ('User_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UTEmployee',
            fields=[
                ('Emp_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='investor_lending',
            name='Inv_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Investor_main'),
        ),
        migrations.AddField(
            model_name='investor_earnings',
            name='Inv_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Investor_main'),
        ),
        migrations.AddField(
            model_name='financials',
            name='Liabilities_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Liabilities'),
        ),
        migrations.AddField(
            model_name='financials',
            name='Reserves_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Reserves'),
        ),
        migrations.AddField(
            model_name='business_addr',
            name='B_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Business_Details'),
        ),
        migrations.AddField(
            model_name='blacklisted',
            name='B_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Business_Details'),
        ),
        migrations.AddField(
            model_name='applicant_details',
            name='Application_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Application_Details'),
        ),
        migrations.AddField(
            model_name='applicant_details',
            name='B_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Business_Details'),
        ),
        migrations.AddField(
            model_name='applicant_addr',
            name='Applicant_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Applicant_Details'),
        ),
        migrations.AddField(
            model_name='app_rejected',
            name='Application_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Application_Details'),
        ),
        migrations.AddField(
            model_name='app_rejected',
            name='B_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Business_Details'),
        ),
        migrations.AddField(
            model_name='app_rejected',
            name='Reason_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='msmeapp.Reject_reason'),
        ),
    ]
